<<<<<<< HEAD
deploy：
    - type: git
      remote: origin
      branch: gh-pages
=======
# Document:
# http://simiki.org/docs/configuration.html

url: 
title: 
keywords: 
description: 
author: 

theme: jekyll-theme-cayman
>>>>>>> ef213dcdcd71d2efab9aa98e30bd91284b8a4c76
