# Document:
# http://simiki.org/docs/configuration.html
deploy:
  - type: git
    remote: 'origin'
    branch: 'gh-pages'

url: 'https://figure-ai.github.io/'
title: '个人wiki'
keywords: 
description: 
author: 
